#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 17 14:26:47 2020

@author: Jules
"""

import pandas as pd
import numpy as np
import glob

path = r'/Users/Jules/Documents/It_Cognition/thesis/Thesis_code/Thesis/static data'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None,
                     error_bad_lines=False,
                     names = ['mmsi', 'length', 'width', 'minDraught', 'maxDraught', 'typeMin', 'typeMax', 'imo', 'shipName', 'aisType', 'a', 'b', 'c', 'd'])
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)
frame.drop_duplicates(subset=['mmsi'], keep='last', inplace=True)

aisTypes = frame['typeMax'].value_counts(dropna=False) # number of AIS types in the dataset
aisTypes_normalized = frame['typeMax'].value_counts(normalize=True, dropna=False) # % of AIS types in the dataset
missingTypes = frame.loc[frame['typeMax'] == 0.0]
missingSize = frame.loc[(frame['length'] == 0) & (frame['width'] == 0)]
missingSizeAndType = missingSize.loc[missingSize['typeMax'] == 0.0]

print('missing types: ', len(missingTypes),  len(missingTypes)*100/len(frame),'%')
print('missing size: ', len(missingSize), len(missingSize)*100/len(frame),'%')
print('missing size and type: ', len(missingSizeAndType), len(missingSizeAndType)*100/len(frame),'%')

frameCopy = frame.loc[(frame['length'] != 0) | (frame['width'] !=0)]


meansAIS = frameCopy.groupby(['typeMax'])['length', 'width'].mean()
stdAIS = frameCopy.groupby(['typeMax'])['length', 'width'].std()
